name: JMPSeniors
favicon: null
layout_spectrum: 0.5750570059753954
typography_spectrum: 0.6330170838627964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed7b50'
    - '#73777a'
    - '#b6c9d3'
    - '#efa383'
  brandStrength: 0.5625
  lightness: 0.9659153867978603
  saturation: 0.7414886381011456
  rhythmicContrast: 0.02947836765088141
purpose: []
